version: '3.8'

services:
  rick-and-morty-case-dev:
    container_name: rick-and-morty-case
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
